### ISSUE TITLE
Client library supporting Configurable Firmata

### ISSUE THREAD

**Issue by mattjlewis** [firmata/ConfigurableFirmata#116]
[diozero](https://www.diozero.com) supports most Firmata features - I can confirm that it works with Configurable Firmata.

**Comment by pgrawehr** [comment]
Thanks for the feedback. Which build did you test? The release version or the latest master?

**Comment by mattjlewis** [comment]
Both latest master as well as latest release (2.10.1).

**Comment by pgrawehr** [comment]
Added link (sorry this took so long)
