### ISSUE TITLE
ESP32 pin 5 digital output missing in Boards.h

### ISSUE THREAD

**Issue by NANDLAB** [firmata/ConfigurableFirmata#122]
Hello everyone,
pin 5 of the ESP32 can also be used as a digital output pin. Can you please adjust it in the Boards.h file?

https://randomnerdtutorials.com/esp32-pinout-reference-gpios/
https://cdn.shopify.com/s/files/1/1509/1638/files/ESP-32_NodeMCU_Developmentboard_Pinout.pdf?v=1609851295

**Comment by pgrawehr** [comment]
Thanks for reporting, I'll take a look.

**Comment by pgrawehr** [comment]
You are right, I'll fix this. I'm in the process of more deeply testing the ESP32, as other features might also not work as expected (eg PWM).
