### ISSUE TITLE
Firmata for Linux hosts

### ISSUE THREAD

**Issue by dimitry-ishenko** [firmata/ConfigurableFirmata#73]
Not sure if this is the right place to ask this... but it would be nice to have Firmata host side implementation for Linux. There are plenty of ARM and x86 based SBCs running Linux (eg RPi) that could benefit from it. 

Then the same protocol can be used to control anything from an Arduino to an RPi or even a full blown PC :smiling_imp:

**Comment by soundanalogous** [comment]
ConfigurableFirmata is for Arduino-based boards. The best place to ask this is probably the firmata/protocol repo since that is architecture agnostic.

**Comment by dimitry-ishenko** [comment]
Thanks @soundanalogous. I will post my question there
